networks:
    excloo:
        external: ENC[AES256_GCM,data:bV7n6g==,iv:N7O57CXPyfblc00AbES3Gex+8ufqw2JDoqBLUiaabls=,tag:Sw0Yp/Cocv1FGA/hCA53XQ==,type:bool]
services:
    caddy:
        environment:
            TS_AUTHKEY: ENC[AES256_GCM,data:TALN/EUMEEmU+K9PftWrWtONc6QaKm++T1U++E4kEUGl6d2xIqtJkZUyGUYawVzVjmXLISEm4MXyts/96w==,iv:xWqtZqAUz9bp4B5NtF7llR1Mw4uWCYyklyJx+PyY1l8=,tag:rtcB6m+bR1+QS3+KJ4JIag==,type:str]
        extra_hosts:
            - ENC[AES256_GCM,data:bnOa2Sv2INtrGgOyX8rDUuxQKQLFe4nI59jYjr4WFMRD,iv:HqwdfS8/VnpmlCUKYi7tJEhnXhi/bTpKqn4bzV3Pyqw=,tag:qaA11JjrrOf7AT3XJOkfJw==,type:str]
        image: ENC[AES256_GCM,data:5tM7bMaYUHWb3hPdUlxH1dx1aFNwwKgpMo7x+gEC,iv:uauNvuMjShgjzs5nqMumVA9yVRkfkwXdCwfCO8uQfto=,tag:DwXHSgupD68B/wnAxTG2yg==,type:str]
        labels:
            caddy.email: ENC[AES256_GCM,data:8SS7SrxT8uxnKmvjdTg=,iv:PaoJtKYLx+SUkKOqqnH7mKRUFSwpBCmMDXhfAD6hqf4=,tag:zriQZfmYwVNvA4ZcE3CgOA==,type:str]
            caddy_0: ENC[AES256_GCM,data:1h1jG1oMi29o1w==,iv:rqfaiGkVHDcrsjTuSRAKyLfyv/yebpcLgrLwsAkjUuU=,tag:M9Ku3SffF/Q4l1Pr5cvfIg==,type:str]
            caddy_0.@is_tailscale: ENC[AES256_GCM,data:FwcjVxogFb43f6HgEmiBgg==,iv:C8aI8tc4/ZkR5KA6q4jvUIEOhEC52gN+h/PuDQhICSY=,tag:VnJ90Ubv0IcLLYX154Wubg==,type:str]
            caddy_0.handle: ENC[AES256_GCM,data:dbZ5gN+gQsMhWVrDMQ==,iv:rnfrH00J8YmdDv2pWDtjdswgaL33m9ESbAtKeKtlqVA=,tag:8Q/CjGILOkYoxerDsAkpsQ==,type:str]
            caddy_0.handle.reverse_proxy: ENC[AES256_GCM,data:AzIuJ7gCDM7D,iv:uLzer2DknIa75A/7j/a1CH26fszMqSfWrZ393Qowyuk=,tag:1g8YVE9JPqIq6CHfmt2b+g==,type:str]
            caddy_0.handle.tls.dns: ENC[AES256_GCM,data:fAxNkyc89g==,iv:ZgoeNmYYx+xIBb3eyDJoP7eoovk1G7SHXMgr61mywhM=,tag:SeFIzdIdBBlO+MbBoJVITA==,type:str]
            caddy_0.handle.tls.dns.acmedns.password: ENC[AES256_GCM,data:uT3ISPNtt2JugBTpT1Ll6sLx7zuYGtvAJm8/9izJEr1VujYqx1MShA==,iv:bpikrpW503fBYVO+qI0n7U7niNkni+wfD5fQ78ntuMw=,tag:fTMNZWbZtplSu0agDWYQWg==,type:str]
            caddy_0.handle.tls.dns.acmedns.subdomain: ENC[AES256_GCM,data:1a82cnXCsD17suNB6dT90eLyFdiH+D/tiJMjtVvKf2ECoujI,iv:uehFJxyi4bZGwyS/YQlKyKk7IwE7IZJ9xr7ZPyz4kXo=,tag:CKpdj+iNzk/PD1GgYbkIIw==,type:str]
            caddy_0.handle.tls.dns.acmedns.username: ENC[AES256_GCM,data:OY/wPF5Im5164B+RKvNzGJvbckFLO5bHzv3UL/HoCyteGqkD,iv:pKzqvsyMeOY84t58WqwGtd+mzT5jjm+copfBLBr5VRA=,tag:kgDmDUj//yUOSbIpgNCnGQ==,type:str]
            caddy_0.handle_1: null
            caddy_0.handle_1.reverse_proxy: ENC[AES256_GCM,data:XdvzK3lRKHMJ,iv:1a0sq3XpmijFeUmiXN8YzAVs1H9ra0hre+/SgTRL0hY=,tag:jov+Vb0/5Tk1W8ZkJ+mayg==,type:str]
        networks:
            - ENC[AES256_GCM,data:s4U5vGM42w==,iv:rDwiD98uHgA7J4V4SxuzS47lhwmUZkXFuOgEcxBtLiI=,tag:Q6yglsbUWozrAAs7CcU82w==,type:str]
            - ENC[AES256_GCM,data:zMio6PTd,iv:U3riJymFUMY5FCYUuEEsYESRLwvZ3N2sJedyAXivowE=,tag:wORtPW9+r1IGX8+vaV9t2g==,type:str]
        ports:
            - ENC[AES256_GCM,data:10h9WeY=,iv:rwCZyeiDmx1O3ugT3nTWlT7Lc2nQgqVJUYTS70RhU1U=,tag:td/zHflBO1x99CQNmZeoNA==,type:str]
            - ENC[AES256_GCM,data:jyqCj/nlug==,iv:MfhhIf5LAPgDNVrpi+AJshRjy4jd3nP5WeIN1U25k7c=,tag:8N2/N8TtgcTVmAytP1+Drg==,type:str]
        restart: ENC[AES256_GCM,data:fl+uImGPYxrz3A/itzE=,iv:MeVyh99lCh9tXwU6x/rhBkDrBKE35HF6l9ojLFLeNGc=,tag:BVMV2hOc72YZ8/1A/rR80w==,type:str]
        volumes:
            - ENC[AES256_GCM,data:ONUk5VNNd4rsllTN9e9GI2HwYMQACxVSFKonuQwdqQGO8ajfTBpe62I=,iv:dDBJvnFMb3n2NL2DEAUHjYvHIHyi3RKiZEy2VZq59Do=,tag:Gks/rd6Wu1LV7PfsQ1xjmg==,type:str]
            - ENC[AES256_GCM,data:66QsbbZqcWiQ0w==,iv:lKo99BTNWhjAKIzao6Oodf2s/PTUQ2y6SJuBoohasqw=,tag:dPpgzQ9js6jrq+Cd+bh23A==,type:str]
volumes:
    data: null
sops:
    age:
        - recipient: age1c7kh5reuq9xegklmskhafapdyag64vjydv05h9qjkn7qm9exj48q7vf37s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MkYyblRiWU9yL0p2MDJO
            SkVLRjNFV1Y4Q0d0TU9zcnVENHlzd3dUSzB3CjRDZzRrRG9QVGxtd1h2THVBR0NE
            aC9CVHBaQUpsMFB0Um1rMmdZUkQ0RXMKLS0tIGt1aXk1bXh4dWtHRU1rWHRteFJi
            OUxycmVtT08yclYxYll0a3NuY0ZiSlkKBSTA2RcJECHfGdfMfFiE91w9YPy1EsXq
            aCv34OfmfIFB8AdAvmfBtYSbNbcgsYSlh8uz0067vMd7Wp2pFG+Ghw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T05:19:04Z"
    mac: ENC[AES256_GCM,data:MZ/M2DTq98oYprzhOK/S8N+ZwPrLxbwhRqHJKOIFhW+TG61g7Vd2JNxhElHke/1J3xCYUhElbb/LSpaAIIiWTsMtJD/hCxgbQ/qbW9zM+5LZiEJ1VOwBTO9SVJag/FNr61+UjVJtzIodDYnUBKxuUFNzW75y+zG8VfsUx5Kvj6E=,iv:uJIVAkmJsUbPS/B1waprAhLZW9uFyhL2wEOsqM9KXAc=,tag:t1Rb99GLMbuR+ZVCk9oITQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2