[[server]]
description = "Mini (AU)"
name = "server-au-mini"
tags = []
[server.config]
address = "https://periphery:8120"
enabled = true
region = "au"

[[server]]
description = "TrueNAS (AU)"
name = "server-au-truenas"
tags = []
[server.config]
address = "https://periphery:8120"
enabled = true
region = "au"

[[server]]
description = "HSP (AU)"
name = "vm-au-hsp"
tags = []
[server.config]
address = "https://periphery:8120"
enabled = true
region = "au"
