[[stack]]
description = "Caddy (server-au-kimbap)"
name = "caddy-server-au-kimbap"
tags = ["no_dns"]
[stack.config]
auto_update = true
repo = "maxexcloo/komodo"
run_directory = "caddy-server-au-kimbap"
server = "server-au-kimbap"
[stack.config.pre_deploy]
command = "SOPS_AGE_KEY=[[AGE_SECRET_KEY]] sops decrypt -i compose.yaml"

[[stack]]
description = "Caddy (server-au-mini)"
name = "caddy-server-au-mini"
tags = ["no_dns"]
[stack.config]
auto_update = true
repo = "maxexcloo/komodo"
run_directory = "caddy-server-au-mini"
server = "server-au-mini"
[stack.config.pre_deploy]
command = "SOPS_AGE_KEY=[[AGE_SECRET_KEY]] sops decrypt -i compose.yaml"

[[stack]]
description = "Caddy (server-au-truenas)"
name = "caddy-server-au-truenas"
tags = ["no_dns"]
[stack.config]
auto_update = true
repo = "maxexcloo/komodo"
run_directory = "caddy-server-au-truenas"
server = "server-au-truenas"
[stack.config.pre_deploy]
command = "SOPS_AGE_KEY=[[AGE_SECRET_KEY]] sops decrypt -i compose.yaml"

[[stack]]
description = "Caddy (vm-au-hsp)"
name = "caddy-vm-au-hsp"
tags = ["no_dns"]
[stack.config]
auto_update = true
repo = "maxexcloo/komodo"
run_directory = "caddy-vm-au-hsp"
server = "vm-au-hsp"
[stack.config.pre_deploy]
command = "SOPS_AGE_KEY=[[AGE_SECRET_KEY]] sops decrypt -i compose.yaml"
