networks:
    excloo:
        external: ENC[AES256_GCM,data:UEIb9Q==,iv:/kgJS38vskocybbPyTsP8EyDRcBeyWyZ43rcmHn5MVM=,tag:ZMGlXqGe/kvBeNBNqczBDQ==,type:bool]
services:
    caddy:
        environment:
            TS_AUTHKEY: ENC[AES256_GCM,data:YuV9MXtHIaPLZaJ2gaSsF2t4iAFHocH1oAOjqzqG0fPeuzTzZfUgWGD1EnR8RcNf/Lo4Ox3JyPl71c3fQQ==,iv:YP+kzHYRwpKPCqlNRNiDKLNR0ynB5rPs6Qm21XQfH7Y=,tag:UzR5zhQ8CtnTK6pc4YYBPA==,type:str]
        extra_hosts:
            - ENC[AES256_GCM,data:H9t1U82OzEOAnnWc6XG0vUD4vezYRSqzwl83vbHrE4Rw,iv:O+ygqZYLFOstbNwjCOhiWSAKSPI1u7ZnlCJlsB0unFk=,tag:L53TRVe/wCr+ArUvZBFosg==,type:str]
        image: ENC[AES256_GCM,data:Yi7frEd5QuYCf7VjaRdo9sP/Hxcz6K17FID88nzb,iv:/KsIXL2xH6L8OSP8tKg9QS3hY+ss+/WlVUzB6xJJSRY=,tag:XTerABkZnMLyESsvUZ7+sQ==,type:str]
        labels:
            caddy.email: ENC[AES256_GCM,data:GXncljLxoGIGTr5Xwbo=,iv:qT02seCa58EkdW+P0x1EeFJpwsx8wbk/xF5wpbX7+hQ=,tag:zgXSGQ03NZ6ry7mJcXmuEw==,type:str]
            caddy_0: ENC[AES256_GCM,data:ONmkbU7SX8NGVQ==,iv:K7oZCgm31adqu+s8MBvQx/ExgZ5D+G0iErK22zcIz4I=,tag:MJIzVUZvNYlnMnCJUOv0Sw==,type:str]
            caddy_0.@is_tailscale: ENC[AES256_GCM,data:uWYIoBphkwiFLrTCcTG3FA==,iv:+SUKQylPk6gIukejID797TJyx6tm7TgrWYnXnv2P2T8=,tag:s6XvmopMtEUkTaKuNl13LA==,type:str]
            caddy_0.handle: ENC[AES256_GCM,data:w+KA9IZJy+VnWoCHoQ==,iv:OeZZThSCG60IB4qwHsZDdFnXFyWw7/CT6R1yw5iPHaE=,tag:CK2oNicDBsR1kMQXtT38rQ==,type:str]
            caddy_0.handle.reverse_proxy: ENC[AES256_GCM,data:blofk//w4HIg,iv:YWIRWIJbRKQmt4wirZ+/Ig4oIsufzf4m6LTKP0wpBqw=,tag:oVkU6j07NUSZAi7TN773bg==,type:str]
            caddy_0.handle.tls.dns: ENC[AES256_GCM,data:V3npW0njuA==,iv:mWEGGvexqMolUFhV5i5JwD1/Zqaayw+QL5/OwkcEj8M=,tag:P6wKv1XxGoWRZRvM6C+dnw==,type:str]
            caddy_0.handle.tls.dns.acmedns.password: ENC[AES256_GCM,data:10ZcqpqS11QkI+OX4tkk+/2edBz3CZgdav67zjcl1gXevQTk7zBRIQ==,iv:I1Hj3bE8FXdq6zH025d7qbjuEwk4sksMnjMn8ak4A5Q=,tag:wtAuV65jQLq4dYma3r1QaQ==,type:str]
            caddy_0.handle.tls.dns.acmedns.subdomain: ENC[AES256_GCM,data:bzjlDwzmF21TvlBytf+pJ8sTpCXXr4ZA6vATG2Qzmw3QEat9,iv:JxasufQIVYIELz6Xw9N5boLgu60265CgftCLgXIOZ0w=,tag:Grd+jMnpbAEyDc64oaI+Sg==,type:str]
            caddy_0.handle.tls.dns.acmedns.username: ENC[AES256_GCM,data:xLqX+65C6yoyEpLmVRJBgoGZhkZ/+4bAD5e2Pl7nnBhrGNry,iv:/6pfkRlo4/pMgo1ngXvbZUXPS0j2jQqfXuHVMgQ1E9o=,tag:ldM4kqMiqedsKoFNy3Ss4w==,type:str]
            caddy_0.handle_1: null
            caddy_0.handle_1.reverse_proxy: ENC[AES256_GCM,data:h7L5VEEJEDtH,iv:k3uK1LuazeWMuvo6idj3Q4DkD7a+KIgCpNM7oBBMBfI=,tag:wUaA5aCRiMheObIOOWO52w==,type:str]
        networks:
            - ENC[AES256_GCM,data:E6rbxRXnWA==,iv:q8Pm4XqXEdXtd/7L5Rxr0+PApEebRicCRZtqxfryer4=,tag:5w62W3XVfQqG2mt/D3ZAiA==,type:str]
            - ENC[AES256_GCM,data:gAMGS/Dl,iv:0DxC38gGKK9KcZBzg76k4fVqKI4cV3kDbXm2yhZBwRk=,tag:Fou3n3z/2JkeW/j8J7UodQ==,type:str]
        ports:
            - ENC[AES256_GCM,data:0e0uAo8=,iv:rwgWKeg+2iGgjnD5Drbo/cdvJH4cs4KZTC8jHA0kryE=,tag:dUmJhozssE+rNriXm9lZ5w==,type:str]
            - ENC[AES256_GCM,data:nQgCbQWNhA==,iv:G9wra3doUEpYeSN5W8+frJfxmC/BdNl2rTfWJLKmXKw=,tag:RDVa1ZIY4w7gt+euQpau7w==,type:str]
        restart: ENC[AES256_GCM,data:OorwHlj0/3srzlx9eeY=,iv:WNt6zXvlWGoGfBHk8PczePIfK0SZ0G/cIo0EPqAvKrU=,tag:MatRMXx++n9uXQg6Y9LDvQ==,type:str]
        volumes:
            - ENC[AES256_GCM,data:TDfIs1I3XMc96fUnX5m4AGDZooVjnuryFJZPcRC5YECo3cZJ702G46o=,iv:jp8Gt8jNg8+pSh147b0V4J8GngbOEX8l5V0qq8oCags=,tag:pLPbynpV5iCuWPqCUs4JQg==,type:str]
            - ENC[AES256_GCM,data:GT739xnvdxXacg==,iv:qGbriuhaFsbUSjE9BqfqsZUd23KoIoxPYKASM3MUQhM=,tag:+/br8PMFnOOM3QEA+7DRQg==,type:str]
volumes:
    data: null
sops:
    age:
        - recipient: age1axdsag3uwpan60zupsghqy57qghhswh4rmtmhlw6gc37054eka5q02fr0m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDN1lLdW9PWHh1YVh4UDJG
            b2lKZ1VQZm1TZHh1LzEwS3FBNkM2eEY1RkNRCmRGQjVVYlFxUjY0OVoyWFlrcWYz
            YXJzR1gvZnpHcHRXZmdmS1lVMW5HT0UKLS0tIGpaWUR4OW5yVXpXRHM5cnhzWDVM
            S2xoZkFtYXJYU2JOMFlCa0F4MXVBalkKpfUcBrE5iNrjkbItAet7KCL2uXEt4eB9
            Uqi+/HT7EnIRAggFbJV1sPIyB6YB5kZaOJjnhWVkiUP8JkUzimgA5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T05:19:04Z"
    mac: ENC[AES256_GCM,data:RxP8SYnc/eP5znP3StF36h7nkITuEDibesRxistxLHMEXyp1uq3y+vxst6eKkaBdLQwXHGB+5Z6Ikso+1dPBIOX3irlOvK8IfIv9udo5TT+CbIj6YiBgPL8DbJ+HX6n18F4Vn9/ZhH+g4N/KQl/ktKOMAFahz5LvZLmIfWv9zWA=,iv:XNQ8ARmunRsPeiMOv61SUv1qJtQ4rr3tvjS8clALR14=,tag:9e4x83rHLhEIfqO+D7WNWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2