networks:
    excloo:
        external: ENC[AES256_GCM,data:ln+IPA==,iv:SmutDV72Z6WuDdMIExfLhtow/fo3koP6LY8h1OGHCJY=,tag:Nsxu+XrnEs0RLAEes46poA==,type:bool]
services:
    caddy:
        environment:
            TS_AUTHKEY: null
        extra_hosts:
            - ENC[AES256_GCM,data:fvRiFWkwa/IXBu6vJ/tvS7kOYn0Uf0a5Yz0CtZlu5o9h,iv:wgtyOlpHuXixIGjTn64lZ4m/VZ0okFntdqPpFMhE51c=,tag:alL0bJ5VMd3HXIU4AwGHsg==,type:str]
        image: ENC[AES256_GCM,data:9as4aeI9YIsU593CQOFUE6l/iPcqKhhk7eDcvus0,iv:ri0P81WvyXw5Ip8+A5nDFjKreDX7AM4iqD8iHyN979M=,tag:DadwSKIYG/RL7p0IJp+nNw==,type:str]
        labels:
            caddy.email: ENC[AES256_GCM,data:fwR3r9ZXE07zyfeY1J8=,iv:UjVcYgNgc6Ti0Xx7IBGNT0k7fCtt9GLMuZMUZBuH6rs=,tag:9R9dU4d+r4mCWAHMaYPseg==,type:str]
            caddy_0: ENC[AES256_GCM,data:XfZAf783uB0OXg==,iv:xpLKPWyFL5ugpzdvsUXgYPaMj8+Blhy+h/iZnI0/Q/M=,tag:6M6+mLwN2qE740bT1XJP0g==,type:str]
            caddy_0.@is_tailscale: ENC[AES256_GCM,data:5YFuVCQ2d0ZMiSo40xj/2g==,iv:C8WlrY+5XrNlCnMgZRFM0mw+vd9SPX/KVJUPnKvLfZU=,tag:oaAYC/6ggpVQ5XMpt20lTw==,type:str]
            caddy_0.handle: ENC[AES256_GCM,data:LasASIEcskHQu7JoTw==,iv:N2e3ExnleLT9uAa9/4UQHnrAM/cnN7bM/y8RlmN5wLo=,tag:BMtuSCgUYingJai6U5Ajhw==,type:str]
            caddy_0.handle.reverse_proxy: ENC[AES256_GCM,data:F4wxwaHoifuc,iv:Qq3owz7XFu2dFaAko6EumAU9pSSeWdAMR4jmFWJgKYk=,tag:KIjnjH/7q7NAzKUCqkdG9A==,type:str]
            caddy_0.handle.tls.dns: ENC[AES256_GCM,data:RomWMwEgIw==,iv:YiTZVl/oSJJ1nhQIgEmpi/xPmhvMfJJJJLqbgAVV0T0=,tag:Ia2jOFypk9xCmSml1DG17A==,type:str]
            caddy_0.handle.tls.dns.acmedns.password: ENC[AES256_GCM,data:JBAvWpvhEGnpbqivGGgoB4n/fyA12Ln4yq52wbgsYa4j+b+8K3qcYw==,iv:PhMK/SvQ74BGK3FX3sHTw8VjrjVzi7VPYdYJGyoCfY4=,tag:50usrQqe1u1EQVmgK+gXHA==,type:str]
            caddy_0.handle.tls.dns.acmedns.subdomain: ENC[AES256_GCM,data:9Gs7lRTxc8Y/hrvizuyoQFJT/GyyberZda84WY7xuxvXAuqI,iv:2XbF45GDUisW/F1WQvxzvY9tPO85W8/kL1oTfef4obY=,tag:KcJmG3IjrWVr8+tOMA7yAg==,type:str]
            caddy_0.handle.tls.dns.acmedns.username: ENC[AES256_GCM,data:gBR7AypjlU/ZxmAoMRWLsBuWb/juSmDEJu+i1OphEzwVO0Wj,iv:DYTVIv6UeUHR3Zk6bqiOcRzmJB9OxmwOQMWxGqgPJhg=,tag:Sxe7SiV3hoy/K/E1zFsweA==,type:str]
            caddy_0.handle_1: null
            caddy_0.handle_1.reverse_proxy: ENC[AES256_GCM,data:27isniwwNW9h,iv:/zYUnzkauSHb0MG1Ti7COW7SowA+PGGq8w3Ku0AEN0Y=,tag:BzDFiWdIWAJMF3M4/jlm0g==,type:str]
        networks:
            - ENC[AES256_GCM,data:A5W5wT8lJw==,iv:CTeJJCQEz5rUFgabVWJJMAmp+5TaWotMq54LDoKxkOI=,tag:cSYOfOrOQIciW1xihh0wFQ==,type:str]
            - ENC[AES256_GCM,data:ifebGdEv,iv:wf2iJKND26ATnhAwaWLhsgrqNLw0q4+wKPOvjRt2zc4=,tag:ltMRoW/AaEMWsUVEDQdKeA==,type:str]
        ports:
            - ENC[AES256_GCM,data:CJf+8Pc=,iv:wATpZflh5jATWrGF7yciH4zgFBuVTJQpFQfTEpUjTu0=,tag:dBN0oD3AWqTB3h/jfrtnow==,type:str]
            - ENC[AES256_GCM,data:eVKlAi6gYQ==,iv:YRHF5/oNJ1SU55ouxrw7CecREGScQulU7d4PibtgNcI=,tag:y8IEfLh1VyJuXcN8RhGsCw==,type:str]
        restart: ENC[AES256_GCM,data:GajywFp/FFPh98ng3A4=,iv:Ie5dmvcDmIAOCoYGauDDdwe+PKN3kACE32iwlgHxhW0=,tag:yxTgtN0ktSbrmpU33B+8OA==,type:str]
        volumes:
            - ENC[AES256_GCM,data:VA7M/oCxRwtdlEIOT4Y/vrXPfh3Z4WbgXft45LRipKjCOp7iSU3dDc0=,iv:2FbKqNMAhyNRE4ZopzW96ICUywksEAZn25MsIxe5SNE=,tag:FL91XQxjOHyzNat+PX82VQ==,type:str]
            - ENC[AES256_GCM,data:XpUCGGcpCbxLgA==,iv:odw6CqIE8hhEdwJNkny34jVHFW53lfShw+sOGCgoAAs=,tag:FlZHZTkoGWm8y8fuX78g2g==,type:str]
volumes:
    data: null
sops:
    age:
        - recipient: age1070kxs3uagsys3vzphqk2tghhnvc8d9z6u49kzprgjpf257fseuqdydjes
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTE5rQU1zdkRKZHphRkd5
            R3g2WXVJUGExc2JBdWRrZVZENXFwanNPR0I4CmxnQUJJaldtNExDQTZDME9uaC9C
            eStKRGo3RWM4aVNIcllhMmtoek9GVGsKLS0tIENNaGlXNC9EOWdKczMvOFZGMWtC
            MU51alAwVlJDVkwrS09wV3IvZzBzZG8KQyuou7Y9fI4IQpcNjKRHsdiSdvnp2mDb
            /l0Nm7XDmXFZ9LYkoqP3xDqXL5Lce+ISVfiqnobV6k20TyiDj2QG8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T01:00:13Z"
    mac: ENC[AES256_GCM,data:rprmafo5q8647Tv/5uGFonl3nXyn5vIEatXjojRDhev542GIjFRMHIM653jxcuAd5jN/WNeSGDYd+iW5xcttpTN6geeSA/OMyjzdn90lWb4qxBDoFY3rIdBYSeiA4dCA2nfS+lzLVeNvvADH8a0Wazb1l151uCJRrG0WHbteJUg=,iv:Pni0tl4QcYcvo75ssg1745pnEsYd62pODWFsijwR3aY=,tag:RleAF9+aON28pIcXKy4vSg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2