networks:
    excloo:
        external: ENC[AES256_GCM,data:KzlTFg==,iv:MWnIrzN8utFPQgEkHDQMMy2dI38NKdrYJeGtID6qVk4=,tag:8hNxlUWjwFZL6A6ZqAvbFA==,type:bool]
services:
    caddy:
        environment:
            TS_AUTHKEY: null
        extra_hosts:
            - ENC[AES256_GCM,data:dus9ga/n+gTmGIG9pXuIwvPgpr/dIZJK+4BnOHCEGFD1,iv:6HPXI1a1SR4adprmntlqULvAay1krLWNij5npxSjcNM=,tag:HBCaCZyEg/p6PnitZqpOYg==,type:str]
        image: ENC[AES256_GCM,data:2kJlWr+54ZA2fo53mxnBmEsYtYZZNJpMZCO89vIr,iv:VXQn+/9BFuk71DrL7jumrsfHOCIhISxaXnaxA0iSVgE=,tag:C5fG9qmS4r3X3fSboaUiPg==,type:str]
        labels:
            caddy.email: ENC[AES256_GCM,data:xhMYFNbVZEdAMQHFaGo=,iv:Lc9bAZySNLQQMtjPw+qLzpqKOumupscl9/8ijhs4AQw=,tag:Dx8FC1jhSN/Yo3s0pfn6ww==,type:str]
            caddy_0: ENC[AES256_GCM,data:YMTEbDama7wH1Q==,iv:4NBNFBiKCkn3y4KYObMBdQcgdRiPmo9a5aHg+SBUr7o=,tag:+QUXDKBB3tRZK9XDoDkNIQ==,type:str]
            caddy_0.@is_tailscale: ENC[AES256_GCM,data:cWbxYMR+CxRQW7LIujTWgQ==,iv:XQlZHEYkBeBnevOAom7IhzdShQAN6+JGLeyJuARUTVo=,tag:FbOMw6DQADScynDU/giHQQ==,type:str]
            caddy_0.handle: ENC[AES256_GCM,data:pl6nuMkkKhDAe9gRbw==,iv:NtLFBmj3kh+UOYY+uFegqrtrCfJ+5N/19o0Vv29/U4k=,tag:8eQPLLBJqSVJv001wIFUXw==,type:str]
            caddy_0.handle.reverse_proxy: ENC[AES256_GCM,data:wQSlRO7Wlssv,iv:v6Z/bz6pdHuG1BLF23cQ0FXwlaLI9iru+P2JLCGZNPI=,tag:bWhlpN65JzU3QMoJTaS/Ew==,type:str]
            caddy_0.handle.tls.dns: ENC[AES256_GCM,data:h/kGF+4bRw==,iv:5RvIO9/bbY91Gj0dCyBbDqf/0CKEFuQVXzcEOWjgIbk=,tag:uHkVb5v7btVZ4yNeWql+Ag==,type:str]
            caddy_0.handle.tls.dns.acmedns.password: ENC[AES256_GCM,data:tuCD1o+A7wf+MepJa7AkKXIWLjgOm/53VY2a1cOoC5lgY/SrZmHOrQ==,iv:Dr8bFWSZxqUCrod6SPh/TIgLDeq2FsPFStM0Lbc+7LI=,tag:mggAq/lw/bdwXq8Ym3wzAg==,type:str]
            caddy_0.handle.tls.dns.acmedns.subdomain: ENC[AES256_GCM,data:ZacvRbVRDdbA4dkoXvbk/W/FXdXWFjAYxH730xH7RbL+doAd,iv:KhS5OJSWZHdzEc5vx/aMqNteEtwv/6n4EzuxgKETOsE=,tag:EA3MAXyTqaqtXQQe2fD3gA==,type:str]
            caddy_0.handle.tls.dns.acmedns.username: ENC[AES256_GCM,data:WJhbNai2NceKE2l27Y037h53ChpTrHUNgBar+dGW0VSiwSIQ,iv:ejFe8z8yrlqvOwlr2H6+DgBGmWknkiYq2fohtPaO6rg=,tag:LTDjvBkDCeLoWV+5LJoYHg==,type:str]
            caddy_0.handle_1: null
            caddy_0.handle_1.reverse_proxy: ENC[AES256_GCM,data:x/13jaXpFdhA,iv:hHwt2/j7U87olkWpgjcgR2s8OG/GjdDrApLZD9wLNG0=,tag:fRr6dU4pbb/66DxLO9iJ5A==,type:str]
        networks:
            - ENC[AES256_GCM,data:iAVwN+K1qA==,iv:Th+0RY/V1ylIkBi6mwYdvLSsuWaaBAeLaUeLU8HBnPk=,tag:8QA9PZmZwnWwTgHSGkr/Fg==,type:str]
            - ENC[AES256_GCM,data:e6sltl0u,iv:8S27be7/Lo4jKNXIxdhf/DFaJoAFqYLe9s6h9BM5pj8=,tag:ikE0d54HyKgT6KEcK2pdUQ==,type:str]
        ports:
            - ENC[AES256_GCM,data:eeApKLY=,iv:5ZU788P6q+oW5y4RpNhOOBxE/28lYwPZMXxgS/1zTTg=,tag:zvUsrb6MEqod7tKL/ZoVdQ==,type:str]
            - ENC[AES256_GCM,data:gCEOAO59eQ==,iv:BMi9QIeXwkRvT52l6xAGF1q+T0olec92z5I7fkK3Hwc=,tag:YHHFMDE+cu56gTTKV3UEWw==,type:str]
        restart: ENC[AES256_GCM,data:Xeu/SIM+wbN/n/UFGMI=,iv:havS4j1Q+Sj4Nv03iqhYzDaUUStoMgDOwdKj+/qAEWs=,tag:/XJKMqkCV1GYU6qKpSiR6g==,type:str]
        volumes:
            - ENC[AES256_GCM,data:aZkFM1uiRULxALm+wEgU24/sMYVlJfSh14Ipe0PEB68OvfnSoFRe8Lo=,iv:uDQQk78kzXN5SA1NLMwIqXJ3GlhnYgUTfI4S/quB0us=,tag:wpLoQckMW9snHhzihJwvOg==,type:str]
            - ENC[AES256_GCM,data:pgABA+8q4rniLw==,iv:FLJOsdfhLHRQ4dYhe/CEUsU35oklDWjfCfdX4+eLgno=,tag:8nF7lU9c1jJeoMlUQA6AOg==,type:str]
volumes:
    data: null
sops:
    age:
        - recipient: age18q9urwh8z3gn40huwpxxxe5s80vqvu8wu8r9xgk8m2zhrydphqnqhtqvms
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYakN1QWNNcXZxSDFzVU5H
            aCs5QUlkUXlUdGhQTkpWN2lFcjVCclkyM2dZCnBNQmdWQmIvWXBDSStyWEM5SUJT
            c0FsUlExS1JjaktkMWZhbWxVUEx0MkkKLS0tIEZzMHdPZ1QxeU9COWt4QWM2V1FI
            RllraWpZVEU3NVJpZFMyV3NhcFpZNUUK4KBInlLEbAWLgHDZzVmH6f8CuwaTRePf
            Kw+hLWDsB9Gpc/dUvFaYFZfHXX/N19U5rzB0RC4xnOiORp7hpB/mfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T01:00:11Z"
    mac: ENC[AES256_GCM,data:b2WWkRVzuVKnPa3AIqyjCCOFSK10XFzpAqyVrvmwnQK8pGGbxrDGGTKYOVLF7hrHFuOrriKTkpOGg1HckiUe6wc8hIW4RCM7u22211RyxEaMegNCao4VlgvDmbJ8MHmj9cIdOmpqhsfe1sh4lFCgdOcgRZvCmGjGtV2bmX4Uj44=,iv:D6xIp8Ipj5vc6avy4mffhy2aVKwCeKaK8jy8vUPlKG0=,tag:p/2r2TVSWGYnGwi9b7rGaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2