networks:
    excloo:
        external: ENC[AES256_GCM,data:Cu7pnA==,iv:80K9I0JQMdG+xdkFvt7yUcKM5NZqEuWGwXxM4YnIMXc=,tag:wNh3blQIrMO+kmVwqVIj3Q==,type:bool]
services:
    caddy:
        environment:
            TS_AUTHKEY: ENC[AES256_GCM,data:m5E/vuHEtg+/RerRY6Cq55ImWodAA+MbeyCA+aMT39b06IPDNMqJY2QbJKpRHFce+cwXkQS+6XFTrTH+Mw==,iv:oZjdQJ0Ih1APVjPtvniZAL3tjmJraK7uwstYytqxwJM=,tag:WStIlDLxNxi1lsqQXSEx5g==,type:str]
        extra_hosts:
            - ENC[AES256_GCM,data:UeSZ4G4kgpNXYPnG6CrBgiBlgqoiegobQ+z20XVLYfnu,iv:N/9d+Dm6QSLC063tvsV/arUKRjRcIgdJcWZJdlKS6Ws=,tag:EcK/4Vc+pPcq9a7AnX+upg==,type:str]
        image: ENC[AES256_GCM,data:jDmc4NeKyQX7ObdvA/FzLejO+Zk3XGZ9c9Z8DMKi,iv:YaHqsK6bxGMeZK1h/8RcWvuRgk2QZeNG5bRctchW7y8=,tag:pyQR8csWD0aSKhmZFTqfcQ==,type:str]
        labels:
            caddy.email: ENC[AES256_GCM,data:8uyc3XZrKkRm83ddEUQ=,iv:83ytYTEqumLkMl/0p0HxhmycU1qhOaetXwX0jcFGRUc=,tag:RGxDQh9qNBxu8PqBahH/jw==,type:str]
            caddy_0: ENC[AES256_GCM,data:jg5Rj8bbtXv2YQ==,iv:zeXdENtuPDfQVqlVje5wSttDzvyqFoxztNsrm3p/tPI=,tag:preGFKoImZml53q2wu9jsQ==,type:str]
            caddy_0.@is_tailscale: ENC[AES256_GCM,data:d7kwrRUuRlx76K2kIXcmJA==,iv:2ojYG3EHgAXavIsUPT0M2qz3+kbERUv8ttluDqpy0eE=,tag:IkNIACWRoBEu9TrDtR1FOQ==,type:str]
            caddy_0.handle: ENC[AES256_GCM,data:CncPfTO4eOnsIWVngA==,iv:437Qen1eXophyTArJUv0KKWi4lQNPdssh4PZLlhoB2U=,tag:EgcwV8xI7Mdpcvn/NKnjVA==,type:str]
            caddy_0.handle.reverse_proxy: ENC[AES256_GCM,data:BOKzt46tZtWC,iv:6yGyMx7KANEiiQ+P+YdH9XNW3yAy8CXShG+iPQKgUAc=,tag:t77heI6YaBSAKKyI3PkUdw==,type:str]
            caddy_0.handle.tls.dns: ENC[AES256_GCM,data:dVx+hwQrBQ==,iv:93FfClo5cU2zD/pFPqw3GeLc/gHyuyVGrBt0Jh+Al/k=,tag:tMdDzNhO4RskqEufvhP+mA==,type:str]
            caddy_0.handle.tls.dns.acmedns.password: ENC[AES256_GCM,data:y/uvwYwghIvB7C7ek3qASWwv9gITmz6yeZsloVa+FYfTOdvYQhevgQ==,iv:iU+tOu0s01I0o7vdB7WmC0zw7UeXxscDVzDJioHdmAU=,tag:eDvzdNBmXW7+cbgdQ0Evjg==,type:str]
            caddy_0.handle.tls.dns.acmedns.subdomain: ENC[AES256_GCM,data:CFjZ1aRpiNA4fZQUI+x/oidiccOHCROTud/Zue5YoOpDIm0J,iv:11c2dp5tyYCSY2pxMSvvl698POu91mVReRvM++E3i94=,tag:aU8O+QlfpJkjcctYqtRKSA==,type:str]
            caddy_0.handle.tls.dns.acmedns.username: ENC[AES256_GCM,data:9ZbH1hspOfAC44r+UCpL2GeKt3QWOMACQBuzcrXVi3yuiZUu,iv:No5EewL7Bn5hGHciDOqXx8OD+rxgKQdstpC8HKTdtsM=,tag:XihxsvGocPfMkf14iXBp4Q==,type:str]
            caddy_0.handle_1: null
            caddy_0.handle_1.reverse_proxy: ENC[AES256_GCM,data:2GaFCv1Fzmzw,iv:RvXT05vo7niDXatSEOdzVzeS9IAvQ/DFE3qCY8m0SBw=,tag:5KeNtGwyNeEdJx9h8mfKBA==,type:str]
        networks:
            - ENC[AES256_GCM,data:tVT9beFWew==,iv:rSwa1E3X7KNG7RMewcTm/2hTjaVJ8TcOnt0NllMTo2M=,tag:oOXGXHXOh24vSRW6pJx5gA==,type:str]
            - ENC[AES256_GCM,data:YzxN4yMc,iv:+r3ePISQWhj2uf8hFhS6mVtChUNcGMwzxya54/I96ZU=,tag:x72MmBQGomBRp+kUAv0orQ==,type:str]
        ports:
            - ENC[AES256_GCM,data:UL1A+BU=,iv:2iJ1YyFViqsizHTUFjXKr46lTLNTXWyCbUExg6LQGVw=,tag:UnH7SzqlKKcSR3hmpsf3Jg==,type:str]
            - ENC[AES256_GCM,data:zveW81GOiw==,iv:IrNUCzMg1NNunZJnKH02OlQ5NZm9vqRj51PzwTBXm6g=,tag:iGCLqUncAHaheNBXgDQKOw==,type:str]
        restart: ENC[AES256_GCM,data:/Y3ES/wIMeoEz54qmdg=,iv:AeKvxn+7+dXqwR1CrAgLP7pk13i1N55NBwLqyVUUmrk=,tag:ZM7GLlNUBXJed9Oko4Qx2Q==,type:str]
        volumes:
            - ENC[AES256_GCM,data:P1jPFOKa3D5XJVrPTpa36F1cxQw10AzPKMKFV7mb/d3z1hmkYp5fLjw=,iv:NFnHbG5YpDtxqGWNQavGVjiERynV6nZDYGuhxLtPwSs=,tag:jvcCufs6tHf+1AVHK3LMkw==,type:str]
            - ENC[AES256_GCM,data:JGoMaLQIZ/j/ow==,iv:efhQtlsU3j5/t+ZYh6nzKlUu3wcgYF2l5reRH1PVEpE=,tag:gZIWydR1iCAHMWhFLKEtiA==,type:str]
volumes:
    data: null
sops:
    age:
        - recipient: age193yn280u0nx9rz7r8snam9vm3y0scjl5lyz69n28a4ruer42399qsyp9y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSd3RMRlVzTkZuRTV1YnJy
            dEsvRGp6WGlvU3pjOUk5K3NZTWhFTkdRUFY0CnViTUR6WWwwdHNGeVM2cTBhMVJa
            MUtuU0lMVXJpeC8xOGpQMmVWNC9WbUEKLS0tIE4yQ0JYeXlMNzVXb2RaM0h1MVlC
            aWRYS0QzT05YV3grMUIwZ1Z6bUQ1UlEKIDhA3oafP5U97mdPMpnEREWvoohTnyvj
            aRJhpCl2ngMqMDTelw+Hm03/4WWg+fdYPFGVp723/yhFmr5FCKjOWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T05:19:04Z"
    mac: ENC[AES256_GCM,data:SZdBUFfgQOSZI9Ud7Jw3lKhIA7KGiDdA6GFc0OTqe2icoygfoxBZNfILl4FHxq1am7JCvkGjISxJrJoyBb9V+1LUlTCznxmzNGC6RcNLTjFwgbW0qT7S3gmYFoxkqS1JC3g22EAYbeeL8dphLLIh6MLxAOQoZhOJ/7M8lijls6c=,iv:BrqxCZB7iOi8lNZl+CnL5narnR9JqEHwWeCtwmv8cYo=,tag:VsCDPEErWkmrA4HbIGT5Fg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2