networks:
    excloo:
        external: ENC[AES256_GCM,data:ia3yeg==,iv:xVzutnpWaf+sQN0j5qRDPoinEAwZyjFvhuN6HSGzG3c=,tag:uYbGJY9GKA0oyTdIB0W7fQ==,type:bool]
services:
    caddy:
        environment:
            TS_AUTHKEY: ENC[AES256_GCM,data:SB46bD/5U1HLBVyQYhqfUOJkRIp8/yPbT12Z7K9UbND2mIQwNCaB3P/YKoXTR+tw9xZgZfxa9WDpsx1D4g==,iv:t7fhnNMzg/Xqdc00vuZoYrNw1RQPTQhIz4c93/rDUbI=,tag:NEDGZQRtd3c5/pWJq+vq6w==,type:str]
        extra_hosts:
            - ENC[AES256_GCM,data:eNu5MwSdySclRE1jhHUswVrdE1FRG7RVYBk2pLKcB2Vz,iv:jKX64hQqTp/wK4UUkXgZ3BxYI5nYsHOwxXmmt1CHq4Y=,tag:eo6XjFbymsflT/k7mLOeyA==,type:str]
        image: ENC[AES256_GCM,data:0HYr+zMo9qt5taDMvWKOHJ4VGTnyUvL8OJLSAUqL,iv:jjzuEZ1ebZf9Hk0Iwu7pn9vBFfdH/5rnlLqTuJJ9cfY=,tag:de/R6gwCbY3mdoemxm0Wpg==,type:str]
        labels:
            caddy.email: ENC[AES256_GCM,data:geuocb10AcUhJRiK46c=,iv:8gxN8y+0ahzSwzOWyQGKFNjGMQ+GBZXy3D8wBvDYZ30=,tag:N0fTYRSpqS3tqBN+fcE0jA==,type:str]
            caddy_0: ENC[AES256_GCM,data:FxlncdMV9yyZQA==,iv:6AhJQkjZBjyGz+t5b8HcACOBrtAN2fVjgEJsYb+/65I=,tag:bVHpOhwk3otPZjxo3iDflw==,type:str]
            caddy_0.@is_tailscale: ENC[AES256_GCM,data:BZvcIQ9xe8FW+H6f4CcfgA==,iv:sPzikgn8sIhBeRCbVSls6cZS5H+dZaATYRExnKzJGBc=,tag:ksdggZUTtqScuGrbWEPWMQ==,type:str]
            caddy_0.handle: ENC[AES256_GCM,data:2NRAXtOMZmTPL+M2kQ==,iv:SGsBYWf0ohFLHRq/nkScjY0A+q2CnPWDaWP2xi4+Lh0=,tag:sneUdjdW9fneeDObohC0ag==,type:str]
            caddy_0.handle.reverse_proxy: ENC[AES256_GCM,data:3zFthLUPCrzh,iv:BtYpXfs4nc9bFGfnI5rJTbn4dNLQkDIFQ/uyVytmQYU=,tag:R3rynlJu9M0ucp+AjK64Zw==,type:str]
            caddy_0.handle.tls.dns: ENC[AES256_GCM,data:C+3sqDbRNw==,iv:C4lWTYvtYSnLKUXEfe1o/PhcG/i0CKd+ruakBZbtBBQ=,tag:Y1uA9mKaqHTgEpf2GqYpNg==,type:str]
            caddy_0.handle.tls.dns.acmedns.password: ENC[AES256_GCM,data:72cPyPMAMJvdTD+itg0AMjLfgWNA4zH1zVDseoxBaANOeyW01z2teQ==,iv:Rz0nox9o8+cxkwsRKHYuGiSO4JKFgd305Kit/msTPU8=,tag:ITLWhoId9hLe38cIz96v7w==,type:str]
            caddy_0.handle.tls.dns.acmedns.subdomain: ENC[AES256_GCM,data:AAIDEjGnokr28ruFYX0nHkRN9pTXF1wgfvLTXMtGVSYbWvCw,iv:T4Nf/PZ6DR6xpJuySrvG0kqI0Vy0oaMsblKYkLoSibM=,tag:ocAmxGN+AQI8M1px8r+1rg==,type:str]
            caddy_0.handle.tls.dns.acmedns.username: ENC[AES256_GCM,data:zQgEQnW8wgApVUD+KLyB9ytnaDkFmHZxgAIZ4xn/gdHlDi48,iv:HZwf/LrBlYtEct8ATBIU+Qlin4wIoAsZs636OXQQ/24=,tag:d/TKR+MtVGLVzvWWem1mNw==,type:str]
            caddy_0.handle_1: null
            caddy_0.handle_1.reverse_proxy: ENC[AES256_GCM,data:fLeqENze3kzr,iv:13ht2xT2boWQ+t+u+9sy5Z2RtZnKirFXivL6tJxpQ30=,tag:FR3nRDaR56nfKmEVKG+iSw==,type:str]
        networks:
            - ENC[AES256_GCM,data:Gk27BVfZAg==,iv:NpbyDzQgcUJSEWteP5nAriT8eZ9xljhE6J2hHXp8nvU=,tag:B2kLlRn+6EOB6827pTS6OA==,type:str]
            - ENC[AES256_GCM,data:tX74Y/ox,iv:JqjyITm0YLUl+j482mpdjQ5YUwYaakhgl+DbCClhhyw=,tag:vd6tDuzq3TG81mftY/KibQ==,type:str]
        ports:
            - ENC[AES256_GCM,data:5VrWxBE=,iv:jF/ZLbc4DnezTZw4aonJt4m20dGsIcMjx4aJpBg4DvI=,tag:jxUL/Wpsa9M3C8lYOx7MTg==,type:str]
            - ENC[AES256_GCM,data:VankLVoNkg==,iv:6JPRXeM3UnGDCATJawHNVm1wUDfj8O+F1lchp+7rJy8=,tag:IXm3W7X5S0mUkZr4bw7NPA==,type:str]
        restart: ENC[AES256_GCM,data:TRUxAQTApIedoeRK1zA=,iv:MuFxZtCzzyZY0MjwSb87DjBgftktqg88cBhxBDl88Jo=,tag:fWA6IcdCuHgWQdceI+F9AA==,type:str]
        volumes:
            - ENC[AES256_GCM,data:WDvSSdAcdtlpWkxh3sRl3uGBSb0iF9V8RTQzGSvWZMpnrOeoju5cO14=,iv:6goBFvN/Ygx/BH9mmScAr4Vc+Qnne/qqhevSbQyyLqw=,tag:qi7k2UM4WbazTjBzG2or4w==,type:str]
            - ENC[AES256_GCM,data:KMAksXLvaEC9zA==,iv:F6SvLhR1DRIXyHIymrlk3nQcJDjrmV2xStWgkCi1Oeg=,tag:z9HzFsHqdDgVs6CFYNEX2w==,type:str]
volumes:
    data: null
sops:
    age:
        - recipient: age1c7kh5reuq9xegklmskhafapdyag64vjydv05h9qjkn7qm9exj48q7vf37s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aUJiRklCd0JTdWhlcVhH
            WW5FSkVnaWlhNmprM1BoYm1pYnN4Ymp3NFN3Cjd4VnNsK0JDZkFWSkJUbkI4eWVL
            UEVUZm5obC90TGJtaHBJNG5icTdVclEKLS0tIGhRWHloaWh6SXp1NHN0NE9uUHJX
            R2RxWldKbnZrRzRxKzdSMHNjV1V0dnMKg/mU/ATZmLeuCXdoTC5FWCKcm9vtnWAN
            wnH9J1Pa3XbIDaRmdsR5syeUM1aaTjkDgCIvS0602m9u7Ktrpk4keA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T05:48:18Z"
    mac: ENC[AES256_GCM,data:F8kcxVqFgrTanG0Midob/pLLXFVy9FdOGn+8PpmcPGAeCnKd0Zq6dIdu1p8RnxKSqPDfoSBC3PYo9PXuaCOfc4WIYADjI+SItjLT1e8FGqbcNUX88i5+hq1R2ryn67wq6QNfLIOtKOXENSHK5bq5OlaDuvK4VR7jKz1bgcC/Pew=,iv:EVGAMXkXfWbfcPQFQ0ZRpK4eFfnHBB4Ps49MUMKKpto=,tag:HeFy1jktQlMB36X0MkpECA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2