networks:
    excloo:
        external: ENC[AES256_GCM,data:QvRiUQ==,iv:lFbO+hHaTa6jJ6XXRBFScTzVjdWo0EMzzloXaiKbeEA=,tag:iXAaali6IM/B6Egqvv+m+g==,type:bool]
services:
    caddy:
        environment:
            TS_AUTHKEY: ENC[AES256_GCM,data:KopIdZRY0FM7YksFWljHpFYevfAM4XBmOhpjbhZnJ9MT87pUnL3BW9k57B7blBRELUTS3kAHis2KqHcMQHQ=,iv:9earN31Nu3jl7go1ylSRNYLkX6LyRsD6eGvnbVdOHIw=,tag:GTJp8QYnkVIAfM5ZcrcEZg==,type:str]
        extra_hosts:
            - ENC[AES256_GCM,data:h8ipfkwj/IOTWGT9b8hh2oXGDRGuWXZqtwfetVnY6Zv0,iv:5ikbjvuhkLFDkxVrGfqoyH4eH7L0u+/HYNlBo8uoCcc=,tag:jJ2Qj8KJuct52qyrPamgsw==,type:str]
        image: ENC[AES256_GCM,data:TQoMJCsCGh7IPUiZQ4szg7qV2wGD4z0cZ98KAORV,iv:jAaDIt0QH/qpiJt6zvkX/+Z9MkBuhUMU4I2wndU0xOI=,tag:+8g470BJPWxWA+bagcY2Fw==,type:str]
        labels:
            caddy.email: ENC[AES256_GCM,data:kmGJM8W6a/3HpiYI//c=,iv:jYAuHvryvVgDlhZKH9hTqSptXycxTcF7eO1ofaTHOxs=,tag:Eih4x1kh20JAF2FtZNh4UQ==,type:str]
            caddy_0: ENC[AES256_GCM,data:j77g24ccZVPdjw==,iv:1tjpRGWCJy2KklaBQbp8rUV3LXLiD32105hN+Lbc52s=,tag:p8Ivc4Uln0DvxOo3cgm69g==,type:str]
            caddy_0.@is_tailscale: ENC[AES256_GCM,data:kKy8SNhTo1Z2wQbeymrHow==,iv:+wIFlWVIXAXqAo4N6NB6Sec8bYAsaayaudVOSmddhP8=,tag:EfSMqr56wYZLFXCKKMW3dQ==,type:str]
            caddy_0.handle: ENC[AES256_GCM,data:Ur00sac3JnlGdF1jQg==,iv:YT793klsiqf5qKvBZROw91heRfY8/RUfUfMVaI/CKfo=,tag:2J19wok9VEfx8nwPaIZJww==,type:str]
            caddy_0.handle.reverse_proxy: ENC[AES256_GCM,data:Q3u25h0yfmx/,iv:dQ817X03e92hlaHRvxGomR4quM1WHhQ5UrFqMhp+tpE=,tag:6rLKczdBD1l3wJ1x+FExqQ==,type:str]
            caddy_0.handle.tls.dns: ENC[AES256_GCM,data:0AYl7FHQdQ==,iv:bkKZrKIs5pFjKh5uaWrHDAnJMLwZq+3JEIs+sU8FTbg=,tag:UpqysrexjkIx+QNkf5CW4Q==,type:str]
            caddy_0.handle.tls.dns.acmedns.password: ENC[AES256_GCM,data:b5b94J5T1vjUKqmiW9LHQW7qTOLTVoFUQ2J3u1S0mDAifK4xZc9iwA==,iv:nGgtOn87+v8mFr+ocCN7iZ8OLzYPui04fCNq+h9y7zc=,tag:lly2DPjLaej09KuDfbf8rQ==,type:str]
            caddy_0.handle.tls.dns.acmedns.subdomain: ENC[AES256_GCM,data:fIZ168BqXwzoXMqbehG+4t3a8Es0X8wLdkY1wTLQx29lsxNs,iv:A+zzJSVv0ZDD4pgz9w3ptRfAEmKOGu/KkiaWvNnyLpg=,tag:5YwBAvmq1trLulEoE1Z2ow==,type:str]
            caddy_0.handle.tls.dns.acmedns.username: ENC[AES256_GCM,data:GPdpY530P0UdqHy+ujRdmBSH+qbVrF17G36EMiUDMvtmaGHm,iv:rXpjmoKsbGj1r9dvFxrnU2lUJH4Yp11vzvRgOGAo7K8=,tag:PDeMWDxU1cQr/EnL1p+VKQ==,type:str]
            caddy_0.handle_1: null
            caddy_0.handle_1.reverse_proxy: ENC[AES256_GCM,data:HC2kfEtixAcV,iv:3k1BCUSE2HxWQNgrgeLfAcQcZri+Cy4shsjFRm98MlE=,tag:FXAjZff7e3nh5hLyRagJQQ==,type:str]
        networks:
            - ENC[AES256_GCM,data:bR4Xi/izMA==,iv:1H1+lG4TfywFSwm+d39reCG6d25IyMwLMXr3FVyLxjw=,tag:sXRcfAoL29LYpDwN5DHxbg==,type:str]
            - ENC[AES256_GCM,data:hUVl1UF7,iv:bvC49gR7Bd4r+fCmzDyDHDgeHGJZxBHEcgqADLtOgG8=,tag:yAJRpHsiiI5/Ve/M7p14FQ==,type:str]
        ports:
            - ENC[AES256_GCM,data:sWSMX2w=,iv:DcL+7AXauDV5dYoHY+qDBb21MuMmdmXysRCr+reEJdo=,tag:7yC6nbJlF10BG2U0whCBIw==,type:str]
            - ENC[AES256_GCM,data:EqMm55yF0g==,iv:Y2/0/AE8BrBza5GiOVU1UIUpek3nsDv7rVbMH1V5LCc=,tag:R5e7otj5C3mINMm1b7T59g==,type:str]
        restart: ENC[AES256_GCM,data:gubi/o4V1+IX0gAu6AA=,iv:ja6EVlLDjy2AGK2Vbq3MaXlnB5t5vAPegpQg5PcbuPw=,tag:GlIsLbm/qP5us1nFENq0DQ==,type:str]
        volumes:
            - ENC[AES256_GCM,data:5DzYAEOf7GqYpd7b5E/BIIcLlA3yaeSoQD5i62Iy/8Gf27DGP7YSPlM=,iv:0JxmKuUd+mmiczuerAcoxpWy8nT7B8bWsDXHxhUSfoE=,tag:lzAVo3GIsNUW3Sjm8ABrrA==,type:str]
            - ENC[AES256_GCM,data:K337iARMSQ4XFg==,iv:MOpEO3i9I7Pis8oLq+2Vl8vTBlAhvotnKrwe1oIVdQs=,tag:OxLDZcNPnkkQfAIkBLhq6Q==,type:str]
volumes:
    data: null
sops:
    age:
        - recipient: age18v76zpwa8g67pnwsq834zljlclzugw0ya0jffrnv30mk77hhz99s9g586e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOXBqcHV2eVB0NHp5S3JL
            eERUd3drY0N2VFhINncva3Nvbk1sdkFYTFJzCnhYWXlrb2VwWndNaU9RRGZjL0Vx
            dXVnblpXRnNsWUJOVUFJRmQxSE9YQ28KLS0tIDF6N0poT2l5MWtLWU9oUGNTUDJX
            QnRzdUNRdTJBV3hjSTROeUZjK1pxazgKtnmESNS7xr3N6NeSvI+zZ/2Exc5OReZz
            iyyHnqJWKO4y+xyRz2mKMcxvU+OZDfiPhIEQ4apT6hZpai1ia+xn6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T05:19:04Z"
    mac: ENC[AES256_GCM,data:gVEkm27/JI7w8PR2f75TcwLLF1FsbfnvsGCYPhwmnV4KKEO9oOV+UkyYjjf3EwjpdUkC4QVefMf6xUU+6kbTy/lfd88/Mmwu1hIBOO2uDqCk/VNyTe6yMsEAJTMhzngFhKfQwtuBeCXn/oSD+dDQ6Uhtya7ngxCts0RQ0UTYT+0=,iv:HdJGSkHfpK5N+0vugcGAeEPUMKWwXrL9sxBAX8ytQiQ=,tag:cL9IH8o0qY9s0c+X7NRdlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2